### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by till** [jjideenschmiede/golexoffice#4]
Hi 👋🏼 

thanks for publishing this code. I wanted to add a few things and send you a PR if contributions are welcome.

Things I wanted to add (so far):

- support for contact of type `person` (private individual)
- support to configure the http client

While using the code, I think there's also some duplicates in the types, but I wanted to ask. Most notable, `ContactBody` and `ContactsReturnContent`. Why not use one type instead?

Thanks,
Till

**Comment by till** [comment]
To elaborate on my client idea:

The reason why I want to configure the client is to be able to set timeouts, etc.. So the code is currently very procedural, and e.g. configuring the `Config` is not possible. By doing that, I am changing your entire code base. So for example:

```go
func (client *Config) AddContact(body) {}
```

Instead of:

```go
func AddContact(body, token) {}
```

Would you be open for that? I know it's basically changing everything. Or do you see another option?

**Comment by till** [comment]
I also saw you have a test case, would you mind adding it?

**Comment by till** [comment]
The request/response code also doesn't seem to take the http status codes into account. I would probably also fix this so the code doesn't fall over trying to decode an "unexpected response".

**Comment by gowizzard** [comment]
Hi @till, thank you for your feedback. We'll have to take a closer look, but unfortunately we don't have the time at the moment. Therefore, I will archive the repository, there has been no further development since 2021.

But I must say that your idea with the configuration of the client is great. We have also implemented this in other projects that we currently still support.

Thank you!

Many greetings
Jonas

**Comment by till** [comment]
@gowizzard No worries, do you have time to look at a PR?

**Comment by till** [comment]
Nevermind, I saw your note about archiving it. I'll keep it in my fork then. :)

For anyone else, who needs it:
https://github.com/hostwithquantum/golexoffice-fork

**Comment by gowizzard** [comment]
Great, that's very nice if you can continue to take care of it. Have fun, if you need anything let me know!
